import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';

import type { Metadata } from "next";
import { Geist, Geist_Mono, EB_Garamond, Poppins } from "next/font/google";
import "./globals.css";
import BootstrapClient from '@/components/BootstrapClient';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebgaramond = EB_Garamond({
  subsets: ['latin'],
});

const poppins = Poppins({
  subsets: ['latin', 'devanagari'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <head>
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@100;600;800&display=swap" rel="stylesheet" />
          <link href="lib/animate/animate.min.css" rel="stylesheet" />
          <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <body className={ebgaramond.className}> */}
          {children}
          <BootstrapClient />
        </body>
      </html>  
    </>
  );
}
