services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news_aggregator_be
    env_file:
      - .env
    volumes:
      - ./backend:/var/www/html
    ports:
      - "${LARAVEL_PORT}:80"
    depends_on:
      - mysql
    networks:
      - news_aggregator_net

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news_aggregator_fe
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "${NEXTJS_PORT}:3000"
    depends_on:
      - laravel
    networks:
      - news_aggregator_net

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - news_aggregator_data:/var/lib/mysql
    networks:
      - news_aggregator_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - news_aggregator_net

volumes:
  news_aggregator_data:

networks:
  news_aggregator_net:
    driver: bridge
